### ISSUE TITLE
SWift 3 

### ISSUE THREAD

**Issue by Ullas9** [ryanfowler/SwiftData#38]
many errors on converting my launguage to swift 3 
kindly let me do the changes and let us know

/SwiftData.swift:1270:21: 'SQLiteDB' is inaccessible due to 'private' protection level

error description on funcition

extension SwiftData.SQLiteDB {
    func bind(objects: [AnyObject], toSQL sql: String) -> (string: String, error: Int?) {

**Comment by ryanfowler** [comment]
I have to apologize for my absence with this repo. 😞 I was unable to work on this for a large part of 2015, and since my return, I haven't been developing in Swift.

Obviously, there are some real problems with the library as it is - a complete re-working is necessary. If there is the interest, I'm looking for one or more people who can update and maintain this codebase, that can be added as collaborators . If anyone would like to contact me privately, you can send me an email directly.

Thanks

**Comment by RegisStGelais** [comment]
Just upgraded to Xcode 8
It works fine when using the "Use Legacy Swift Language Version" build setting.

When I have some spare time, I will try it in Swift 3 mode.

**Comment by Ullas9** [comment]
we have converted as much as possible and it works it might be a issue of the syntax changes of swift3

**Comment by MajestikM** [comment]
After running the Swift 3.0 migration tool the following errors occurred: http://stackoverflow.com/questions/40380068/swiftdata-sqlite-wrapper-broken-with-swift-3-0#comment68013680_40380068

@Ullas9 do you already have the fixed code? I would very much appreciate it.

**Comment by Ullas9** [comment]
sure soon i will 

```
On Wednesday, 2 November 2016 8:02 PM, MajestikM <notifications@github.com> wrote:
```

 After running the Swift 3.0 migration tool the following errors occurred: http://stackoverflow.com/questions/40380068/swiftdata-sqlite-wrapper-broken-with-swift-3-0#comment68013680_40380068@Ullas9 do you already have the fixed code? I would very much appreciate it.—

**Comment by amdroid007** [comment]
Has anyone made any updates? We are using SwiftData and can't update to Swift 3 until SwiftData is  updated. I would greatly appreciate if someone can point me to a fork with a Swift 3 version.

**Comment by Ullas9** [comment]
i do have it but it will be great if we discuss before forking it my name is ullas 918422958889
 

    On Sunday, 8 January 2017 7:02 AM, amdroid007 <notifications@github.com> wrote:
 

 Has anyone made any updates? We are using SwiftData and can't update to Swift 3 until SwiftData is updated. I would greatly appreciate if someone can point me to a fork with a Swift 3 version.—

**Comment by ganesh1987** [comment]
In future can we expect Swift 3.0 migration of SwiftData ?

**Comment by Ullas9** [comment]
yes

**Comment by amdroid007** [comment]
@Ullas9 any updates to the 3.0 migration on SwiftData? Swift 3.1 just came out, and I am sure knowing apple, they are going to phase out Swift 2 soon - besides most other frameworks are now in 3.0, so I would really like to migrate to Swift 3 for an app and this one is holding me back. I tried doing the migration myself unfortunately I am more of an Android developer myself so some of the errors are beyond my understanding of Swift's quirks.

Please do a 3.0 fork if possible - or post a diff if possible?

J

**Comment by Ullas9** [comment]
amdroid007 as your name says i can understand u r the androids, i have a lib of 3.0 would need to get permission and will fork

**Comment by desrochers** [comment]
I ended up getting SwiftData working with Swift 3.0 today. I have not really put it through its paces yet, but it has worked for me so far.

https://pastebin.com/AG0HuTNa

For the most part, Xcode can figure out the conversion process. But the getColumnValue() function needed some manual intervention.

**Comment by Mayur-Bendale** [comment]
@desrochers Thanks. Your code helps me a lot. :)
