### ISSUE TITLE
How to use existing database

### ISSUE THREAD

**Issue by conxsys** [ryanfowler/SwiftData#4]
I cannot get SwiftData to use an already existing database that contains data. I have renamed it to SwiftData.sqlite and placed it in the Supporting Files folder in my project (I have tried a few other locations as well). When I try to query the Players table:

let (resultSet, err) = SD.executeQuery("SELECT \* FROM PLAYERS")

I get the error:

SwiftData Error -> During: SQL Prepare
                -> Code: 1 - SQL error or missing database
                -> Details: no such table: PLAYERS

**Comment by Lopdo** [comment]
I think this should be official part of the (otherwise awesome) project, along with option to specify name of file.
