### ISSUE TITLE
Swift Data not working in XCode 11, iOS 13

### ISSUE THREAD

**Issue by moizirshad** [ryanfowler/SwiftData#45]
Not able to fetch data in XCode 11. I am currently working on Swift 5. It's creating a table properly but not able to save data into the database. 
It's working properly on XCode 10.3
But not working on XCode 11.

**Comment by RegisStGelais** [comment]
It works fine on my side with Xcode 11.1 and iOS 13 but I compile in Swift 4.2.
The issue is probably related to Swift 5.

**Comment by moizirshad** [comment]
@RegisStGelais Please check it on Swift 5.

**Comment by moizirshad** [comment]
@RegisStGelais Please send me your Swift Data updated file. I am facing the same issue on Swift 4.2 also. 
It's working fine on XCode 11, iOS 12. But not able to work on XCode 11, iOS 13.

**Comment by moizirshad** [comment]
Found Solution. 

Replace this line to line number 1307. 

`let newStr = data.map { String(format: "%02.2hhx", $0) }.joined()`
